export default {
    action: {
        order: require('../../assets/images/actions/btn-order.png'),
        add: require('../../assets/images/actions/add.png'),
        add_square: require('../../assets/images/actions/btn-add.png'),
        add_square_active: require('../../assets/images/actions/btn-add-active.png'),
        add_round_active: require('../../assets/images/actions/btn-add-round-active.png'),
        sub_square: require('../../assets/images/actions/btn-sub.png'),
        sub_round: require('../../assets/images/actions/btn-sub-round.png'),
        sub_round_active: require('../../assets/images/actions/btn-add-round-active.png'),
        add_more: require('../../assets/images/actions/btn-add-1.png'),
        delete: require('../../assets/images/actions/btn-delete.png'),
        edit: require('../../assets/images/actions/btn-edit.png'),
        edit_active: require('../../assets/images/actions/btn-edit-active.png'),
        eye: require('../../assets/images/actions/btn-eye.png'),
        eye_off: require('../../assets/images/actions/btn-eye-off.png'),
        filter: require('../../assets/images/actions/btn-filter.png'),
        flash: require('../../assets/images/actions/btn-flash.png'),
        flash_off: require('../../assets/images/actions/btn-flash-off.png'),
        left_long: require('../../assets/images/actions/btn-left-long.png'),
        more: require('../../assets/images/actions/btn-more.png'),
        note_active: require('../../assets/images/actions/btn-note-active.png'),
        reload: require('../../assets/images/actions/btn-reload.png'),
        right: require('../../assets/images/actions/btn-right.png'),
        right_long: require('../../assets/images/actions/btn-right-long.png'),
        save: require('../../assets/images/actions/btn-save.png'),
        scan: require('../../assets/images/actions/btn-scan.png'),
        search: require('../../assets/images/actions/btn-search.png'),
        search_active: require('../../assets/images/actions/btn-search-active.png'),
        trash: require('../../assets/images/actions/btn-trash.png'),
        voucher: require('../../assets/images/actions/btn-voucher.png'),
        calendar: require('../../assets/images/actions/calendar.png'),
        menu: require('../../assets/images/actions/menu.png'),
        print: require('../../assets/images/actions/btn-print.png'),
        off: require('../../assets/images/actions/off.png'),
    },
    customer: {
        customer: require('../../assets/images/customer/customer.png'),
    },
    info: {
        success: require('../../assets/images/info/success.png'),
        error: require('../../assets/images/info/error.png'),
        info: require('../../assets/images/info/info.png'),
    },
    default: {
        category: require('../../assets/images/default/category.png'),
        product: require('../../assets/images/default/product.png'),
        area: require('../../assets/images/default/area.png'),
    },
    intro: {
        _1: require('../../assets/images/intro/intro-1.png'),
        _2: require('../../assets/images/intro/intro-2.png'),
        _3: require('../../assets/images/intro/intro-3.png'),
    },
    logo: {
        full: require('../../assets/images/logo/logo-full.jpg'),
        short: require('../../assets/images/logo/logo-short.png'),
    },
    menu: {
        barcode: require('../../assets/images/menu/barcode.png'),
        bill: require('../../assets/images/menu/bill.png'),
        home: require('../../assets/images/menu/home.png'),
        payment: require('../../assets/images/menu/payment.png'),
        setting: require('../../assets/images/menu/setting.png'),
        table: require('../../assets/images/menu/table.png'),
    },
    method_payment: {
        bank: require('../../assets/images/method_payment/bank.png'),
        cash: require('../../assets/images/method_payment/cash.png'),
        member: require('../../assets/images/method_payment/member.png'),
        momo: require('../../assets/images/method_payment/momo.png'),
    },
    order_type: {
        delivery: require('../../assets/images/order_type/delivery.png'),
        take_away: require('../../assets/images/order_type/take_away.png'),
        in_table: require('../../assets/images/order_type/in_table.png'),
    },
    setting: {
        code: require('../../assets/images/setting/code.png'),
        email: require('../../assets/images/setting/email.png'),
        info: require('../../assets/images/setting/info.png'),
        phone: require('../../assets/images/setting/phone.png'),
        website: require('../../assets/images/setting/website.png'),
    },
    advance: require('../../assets/images/advance.png'),
    check_active: require('../../assets/images/check-active.png'),
    item_select: require('../../assets/images/item_select.png'),
    clock: require('../../assets/images/clock.png'),
    grid_2: require('../../assets/images/grid-2.png'),
    information: require('../../assets/images/information.png'),
    radio: require('../../assets/images/radio.png'),
    radio_active: require('../../assets/images/radio-active.png'),
    splash: require('../../assets/images/splash.png'),
    switch: require('../../assets/images/switch.png'),
    switch_active: require('../../assets/images/switch-active.png'),
    total_table: require('../../assets/images/total-table.png'),
    vnd: require('../../assets/images/vnd.png'),
    check_warning: require('../../assets/images/check-warning.png'),
    empty: require('../../assets/images/empty.png'),
    promotion: {
        ship: require('../../assets/images/promotion/ship.png'),
        discount: require('../../assets/images/promotion/discount.png'),
    },
    bg_scan: require('../../assets/images/bg-scan.png'),
    background: {
        sidebar: require('../../assets/images/background/sidebar-bg.png'),
    },
    flag_en: require('../../assets/images/flag-en.png'),
    flag_vn: require('../../assets/images/flag-vn.png'),
    network_fail: require('../../assets/images/network_fail.png'),
};
